name: CI (Ubuntu)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build with Makefile
        run: |
          make

      - name: Copy test data files to build directory
        run: |
          mkdir -p build
          cp $(find -name "*.dat") build/ || true
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          make test
        working-directory: ${{ github.workspace }}

      - name: Install binary and man page
        run: |
          sudo make install

      - name: Check man page
        run: |
          man -w diff_numerics
          man diff_numerics | head -20

      - name: Uninstall binary and man page
        run: |
          sudo make uninstall

      - name: Check that binary and man page are uninstalled
        run: |
          if man -w diff_numerics; then
            echo "ERROR: man page still present after uninstall"
            exit 1
          else
            echo "Man page correctly uninstalled"
          fi
